version: '3.4'

services:
  ahmedalimsolimansd:
    image: ahmedalimsolimansd/portfolio:5
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000